export const randomFacts = [
    "Only 7% of high school athletes go on to play a varsity sport in college.",
    "There are over 1,000 colleges with men’s soccer programs in the US.",
    "NCAA Division I schools can offer up to 9.9 full scholarships for men's soccer.",
    "Division III schools do not offer athletic scholarships, but they can provide academic or need-based aid.",
    "The National Letter of Intent (NLI) is a binding agreement between a student-athlete and a college.",
    "You can start contacting college coaches as early as your freshman year of high school.",
    "College coaches can start reaching out to recruits on June 15th after their sophomore year.",
    "Athletes can use official visits to visit a college at the expense of the school. You're allowed up to 5 official visits.",
    "Recruiting rules differ for each NCAA division, so it's important to understand the guidelines for your target division.",
    "An unofficial visit is a visit to a college that is paid for by the athlete, not the college.",
    "The NCAA Eligibility Center certifies the academic eligibility of athletes for Division I and II schools.",
    "Only 2% of high school athletes receive athletic scholarships for college.",
    "Most soccer scholarships are partial, not full, and athletes often combine athletic, academic, and need-based aid.",
    "Walking on means joining the team without a scholarship, but you can still earn one later in your career.",
    "The recruiting process for Division III schools often starts later than for Division I and II.",
    "NCAA coaches are not allowed to attend showcases or tournaments during certain 'dead periods.'",
    "Having a highlight video is critical for athletes in sports like soccer where coaches can't attend every game.",
    "Coaches typically recruit multiple players for each position, so it's important to stand out early.",
    "Maintaining a high GPA can greatly increase your chances of receiving a scholarship.",
    "Some schools may offer preferred walk-on spots, which guarantee a spot on the team without scholarship money.",
    "The majority of recruiting happens during the athlete’s junior year of high school.",
    "Many scholarships are renewable yearly, so keeping good academic and athletic standing is crucial.",
    "NAIA schools also offer competitive soccer programs and scholarships, and they have different recruiting rules from the NCAA.",
    "Social media is becoming increasingly important in the recruiting process—keep your profiles professional.",
    "NCAA limits how many times a coach can contact an athlete during the recruiting period.",
    "International student-athletes also need to meet NCAA eligibility requirements to compete.",
    "The NCAA mandates that athletes must be amateurs—professional athletes are not eligible to compete.",
    "Coaches often look for leadership qualities and how athletes respond to adversity when recruiting.",
    "Being proactive in the recruiting process, like emailing coaches, can help you stand out.",
    "Most athletes do not get recruited solely from highlight videos—attending camps and showcases is important.",
    "Some schools have large rosters, and not every player gets equal playing time, especially in the first year.",
    "The Ivy League does not offer athletic scholarships, but athletes can receive need-based financial aid.",
    "College coaches may only be able to offer verbal commitments before you officially sign a National Letter of Intent.",
    "Verbal offers from coaches are not binding, but NLIs are.",
    "It’s important to research the academic programs of the schools you’re interested in as much as their athletics.",
    "Some athletes redshirt their freshman year, meaning they practice with the team but do not play in games.",
    "Scholarships are not always guaranteed for four years—many are renewable annually based on performance.",
    "It’s important to be flexible in your recruiting process—your top school choice might change as you learn more.",
    "Attending summer camps hosted by colleges can increase your chances of getting noticed.",
    "Coaches can begin offering scholarships as early as sophomore year for some sports.",
    "Division II schools often offer a balance of athletic and academic life, with scholarships available.",
    "Athletes in less common sports, like golf or tennis, might have more scholarship opportunities compared to more popular sports.",
    "Character and academics are just as important as athletic ability in the recruiting process.",
    "The transfer portal allows college athletes to transfer schools more easily and still maintain eligibility.",
    "Some student-athletes commit early to their chosen school, sometimes even before their junior year.",
    "Not all colleges participate in the National Letter of Intent program, including Ivy League schools.",
    "The recruiting calendar has different periods such as quiet periods, dead periods, and contact periods.",
    "Division III schools recruit differently than Division I, often focusing more on academics and fit than just athletics.",
    "Most colleges recruit athletes who can bring something special both on and off the field.",
    "Being a multi-sport athlete can sometimes increase your recruiting potential.",
    "The recruiting process can be long, often taking several months to years."
  ];
  